### ISSUE TITLE
php7.2 web模式下 Cannot redeclare function 

### ISSUE THREAD

**Issue by ggg4566** [fate0/xmark#4]
php7.2 cli模式下运行正常，但是web模式下就会出现 Cannot redeclare , phpinfo查看扩展是启用状态，这是什么问题吗

**Comment by ggg4566** [comment]
测试一下应该还是与opcode冲突的问题，禁用就ok了

**Comment by fate0** [comment]
#3 和这问题一样，应该已经修复了，更新代码试试看。
